'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System



''' <summary>
'''   A strongly-typed resource class, for looking up localized strings, etc.
''' </summary>
' This class was auto-generated by the StronglyTypedResourceBuilder
' class via a tool like ResGen or Visual Studio.
' To add or remove a member, edit your .ResX file then rerun ResGen
' with the /str option, or rebuild your VS project.
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")>
<Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
Friend Class Form1

    Private Shared resourceMan As Global.System.Resources.ResourceManager

    Private Shared resourceCulture As Global.System.Globalization.CultureInfo

    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
    Friend Sub New()
    End Sub

    ''' <summary>
    '''   Returns the cached ResourceManager instance used by this class.
    ''' </summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Form1", GetType(Form1).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property

    ''' <summary>
    '''   Overrides the current thread's CurrentUICulture property for all
    '''   resource lookups using this strongly typed resource class.
    ''' </summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Friend Shared Property Culture As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set(value As Global.System.Globalization.CultureInfo)
            resourceCulture = value
        End Set
    End Property

    ''' <summary>
    '''   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
    ''' </summary>
    Friend Shared ReadOnly Property notifyIcon_Icon As Drawing.Icon
        Get
            Dim obj As Object = ResourceManager.GetObject("notifyIcon.Icon", resourceCulture)
            Return CType(obj, Drawing.Icon)
        End Get
    End Property

    ''' <summary>
    '''   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
    ''' </summary>
    Friend Shared ReadOnly Property notifyIcon_TrayLocation As Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("notifyIcon.TrayLocation", resourceCulture)
            Return obj
        End Get
    End Property
End Class
