'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Properties


    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings())), Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("impinj-15-50-20")>
        Public Property Hostname As String
            Get
                Return CStr(Me("Hostname"))
            End Get
            Set(value As String)
                Me("Hostname") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("https://localhost:44372/")>
        Public Property Socket As String
            Get
                Return CStr(Me("Socket"))
            End Get
            Set(value As String)
                Me("Socket") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("3000")>
        Public Property Worktime As Integer
            Get
                Return CInt(Me("Worktime"))
            End Get
            Set(value As Integer)
                Me("Worktime") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("in")>
        Public Property Type As String
            Get
                Return CStr(Me("Type"))
            End Get
            Set(value As String)
                Me("Type") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("5000")>
        Public Property intervalTime As Integer
            Get
                Return CInt(Me("intervalTime"))
            End Get
            Set(value As Integer)
                Me("intervalTime") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("1")>
        Public Property AtentaPortIN As Integer
            Get
                Return CInt(Me("AtentaPortIN"))
            End Get
            Set(value As Integer)
                Me("AtentaPortIN") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.DefaultSettingValueAttribute("9")>
        Public Property AtentaPortOut As Integer
            Get
                Return CInt(Me("AtentaPortOut"))
            End Get
            Set(value As Integer)
                Me("AtentaPortOut") = value
            End Set
        End Property
    End Class
End Namespace
